version: "3"

services:
  node-server:
    tty: true
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 4200:4200
    restart: unless-stopped
    volumes:
      - ./:/app
